-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.demandes_conge
(
    id serial NOT NULL,
    utilisateurid integer NOT NULL,
    date_debut timestamp without time zone NOT NULL,
    date_fin timestamp without time zone NOT NULL,
    motif text COLLATE pg_catalog."default" NOT NULL,
    statut character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'En attente'::character varying,
    date_soumission timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT demandes_conge_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.plannings_conge
(
    id serial NOT NULL,
    utilisateurid integer NOT NULL,
    date_debut timestamp without time zone NOT NULL,
    date_fin timestamp without time zone NOT NULL,
    motif text COLLATE pg_catalog."default" NOT NULL,
    date_creation timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT plannings_conge_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.rappels
(
    id serial NOT NULL,
    message text COLLATE pg_catalog."default" NOT NULL,
    date_rappel timestamp without time zone NOT NULL,
    utilisateurid integer NOT NULL,
    CONSTRAINT rappels_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.utilisateurs
(
    id serial NOT NULL,
    nom character varying(100) COLLATE pg_catalog."default" NOT NULL,
    email character varying(150) COLLATE pg_catalog."default" NOT NULL,
    role character varying(50) COLLATE pg_catalog."default" NOT NULL,
    motdepasse text COLLATE pg_catalog."default",
    superieurid integer,
    CONSTRAINT utilisateurs_pkey PRIMARY KEY (id),
    CONSTRAINT utilisateurs_email_key UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS public.validations
(
    id serial NOT NULL,
    demandecongeid integer NOT NULL,
    valideurid integer NOT NULL,
    statut character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'En attente'::character varying,
    commentaire text COLLATE pg_catalog."default",
    datevalidation timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ordre_validation integer NOT NULL DEFAULT 1,
    CONSTRAINT validations_pkey PRIMARY KEY (id)
);

COMMENT ON COLUMN public.validations.ordre_validation
    IS 'Ordre de validation dans le workflow (1 = premier niveau, 2 = second niveau, etc.)';

ALTER TABLE IF EXISTS public.demandes_conge
    ADD CONSTRAINT fk_utilisateur_demande FOREIGN KEY (utilisateurid)
    REFERENCES public.utilisateurs (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.plannings_conge
    ADD CONSTRAINT fk_utilisateur_planning FOREIGN KEY (utilisateurid)
    REFERENCES public.utilisateurs (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.rappels
    ADD CONSTRAINT fk_utilisateur_rappel FOREIGN KEY (utilisateurid)
    REFERENCES public.utilisateurs (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.utilisateurs
    ADD CONSTRAINT fk_superieur FOREIGN KEY (superieurid)
    REFERENCES public.utilisateurs (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.validations
    ADD CONSTRAINT fk_demande_validation FOREIGN KEY (demandecongeid)
    REFERENCES public.demandes_conge (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.validations
    ADD CONSTRAINT fk_valideur_validation FOREIGN KEY (valideurid)
    REFERENCES public.utilisateurs (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;